version: '3.8'

services:
  myapp:
    container_name: myapp
    build:
      dockerfile: development.Dockerfile
    restart: always
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - ./:/myapp
